### ISSUE TITLE
ISC license not included in zip

### ISSUE THREAD

**Issue by pnorman** [mapbox/directions-icons#4]
The ISC license requires the copyright notice and license be distributed with the software, and the zip file doesn't include it.

I'd do a PR, except that as per @bhousel "tbh that one should probably be CC0 also"

cc @tomh

**Comment by bhousel** [comment]
Yes, by "also" I meant that this project could probably be CC0 like [maki](https://github.com/mapbox/maki).  

cc @tmcw

**Comment by tmcw** [comment]
👍 yep, CC0 is appropriate
